### ISSUE TITLE
有些问题想请教一下

### ISSUE THREAD

**Issue by N1necats** [fengyuecanzhu/Sdu-Seat#1]
我用vscode运行的，最后显示：
BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
但是座位好像没约上，可能是哪出了问题呢？
{
  "userid": "202000000000",
  "passwd": "N1necats11,,",
  "deviceId": "322890634897f0df8aa18a7f57a050b9",
  "area": "威海馆-主楼(3-10)",
  "seats": {
    "十楼阅览室": ["087", "088"]
  },
  "filterRule": "",
  "only": true,
  "time": "12:30:00",
  "period": "12:30-22:30",
  "retry": 10,
  "retryInterval": 1,
  "delta": 0,
  "bookOnce": true,
  "webVpn": false
}

**Comment by N1necats** [comment]
完整运行结果：
PS C:\vsjava> cmd /c "c:\vsjava\VSjava\lib\sdu\Sdu-Seat-2.7\gradlew.bat"

> Task :help

Welcome to Gradle 7.4.2.

Directory 'C:\vsjava' does not contain a Gradle build.

To create a new build in this directory, run gradlew init

For more detail on the 'init' task, see https://docs.gradle.org/7.4.2/userguide/build_init_plugin.html

For more detail on creating a Gradle build, see https://docs.gradle.org/7.4.2/userguide/tutorial_using_tasks.html

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/7.4.2/userguide/command_line_interface.html    

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed

**Comment by fengyuecanzhu** [comment]
你这是想自己编译吗，上面的输出都是编译的输出（而且目录还不对）

运行的话直接下载[jar文件](https://github.com/fengyuecanzhu/Sdu-Seat/releases/download/v2.7/sdu-seat-2.7.jar)，然后在当前文件目录打开终端，运行命令即可：
```shell
java -jar sdu-seat-2.7.jar 你的配置文件路径
```

**Comment by N1necats** [comment]
应该是我gradle没有配置好，之前试过直接运行“gradlew.bat"，显示
Task :help
Welcome to Gradle 7. 1.
To run a build, run gradlew <task> .. .
To see a list of available tasks, run gradlew tasks
To see a list of command-line options, run gradlew - -help
To see more detail about a task, run gradlew help --task <task>
For troubleshooting, visit https://help. gradle. org
BUILD SUCCESSFUL in 2s
act ionable task:1 execut ed
-> 0% WAITING
IDLE
然后闪退了···

**Comment by N1necats** [comment]
您好，请问现在运行完显示这个，然后还是没约上怎么办呢？
> Task :help

Welcome to Gradle 7.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

**Comment by fengyuecanzhu** [comment]
都说了你这是编译，不是运行，你都完全没有运行怎么选座，你按这个来运行

> 你这是想自己编译吗，上面的输出都是编译的输出（而且目录还不对）
> 
> 运行的话直接下载[jar文件](https://github.com/fengyuecanzhu/Sdu-Seat/releases/download/v2.7/sdu-seat-2.7.jar)，然后在当前文件目录打开终端，运行命令即可：
> 
> ```shell
> java -jar sdu-seat-2.7.jar 你的配置文件路径
> ```

**Comment by fengyuecanzhu** [comment]
> 应该是我gradle没有配置好，之前试过直接运行“gradlew.bat"，显示 Task :help Welcome to Gradle 7. 1. To run a build, run gradlew .. . To see a list of available tasks, run gradlew tasks To see a list of command-line options, run gradlew - -help To see more detail about a task, run gradlew help --task For troubleshooting, visit https://help. gradle. org BUILD SUCCESSFUL in 2s act ionable task:1 execut ed -> 0% WAITING IDLE 然后闪退了···

编译才需要gradle，运行不用这个，装个java就行

**Comment by N1necats** [comment]
卧槽牛逼，哥，我终于搞好了，你是我的神，考上了请你吃饭！！

**Comment by N1necats** [comment]
ERROR             json解析错误，内容如下:



<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="renderer" content="webkit">
        <link rel="stylesheet" type="text/css" href="/cas/comm/icon/icon.css">
    <link rel="stylesheet" type="text/css" href="/cas/comm/icon/ie7/ie7.css">
    <link rel="stylesheet" type="text/css" href="/cas/comm/css/login.css">
        <script type="text/javascript" src="/cas/comm/icon/ie7/ie7.js"></script>        <title>系统提示</title>
</head>
<body class="bind_bg" style="height: 100%;">
    <div class="bind_container">
        
        <div class="password_container_header">
                <div class="password_header_inside">
                        <p class="logo-picture">
                                <img class="password_logo_pic" src="/cas/comm/images/head_logo.png">
                        </p>
                        <p class="logo-point"></p>
                        <p class="logo-text">系统提示</p>
                        <p class="clear"></p>
                </div>
        </div>
        <div class="logo_light"></div>
        <div class="bind_main_container">
            <img class="authorise_img" src="/cas/comm/image/unauthorise.png">
            <span class="authorise_title">请求出错</span>
            <p class="unauthorise_p">抱歉！您的请求出现了异常，请稍后再试。</p>
            <input class="bind_button left bind_button_1 authorise_button" type="button" value="重新登录" id="btn_login">
            <input class="bind_button right bind_button_2 authorise_button" type="button" value="关闭页面" id="btn_close">
        </div>
    </div>

    <script type="text/javascript" src="/cas/comm/js/jquery.min.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#btn_close").click(function(){
                window.open("about:blank","_self").close();
        });

        $("#btn_login").click(function(){
                location.href="/cas/logout?service=http://service.sdu.edu.cn/tp_up/view?m=up";
        });

        var setting = {
                imageWidth : 1680,
                imageHeight : 1050
        };
        var init = function() {
                var windowHeight = $(window).height();
                var windowWidth = $(window).width();
//              $(".login_conatiner").height(windowHeight).width(windowWidth);
                $(".login_conatiner").css("height",windowHeight);
                $(".login_conatiner").css("width",windowWidth);

//              $("#container_bg").height(windowHeight).width(windowWidth);
                $("#container_bg").css("height",windowHeight);
                $("#container_bg").css("width",windowWidth);

//              $("#login_right_box").height(windowHeight);
                $("#login_right_box").css("height",windowHeight);

                var imgW = setting.imageWidth;
                var imgH = setting.imageHeight;
                var ratio = imgH / imgW; // 图片的高宽比

                imgW = windowWidth; // 图片的宽度等于窗口宽度
                imgH = Math.round(windowWidth * ratio); // 图片高度等于图片宽度 乘以 高宽比

                if (imgH < windowHeight) { // 但如果图片高度小于窗口高度的话
                        imgH = windowHeight; // 让图片高度等于窗口高度
                        imgW = Math.round(imgH / ratio); // 图片宽度等于图片高度 除以 高宽比
                }

                $(".login_img_01").width(imgW).height(imgH); // 设置图片高度和宽度
        };

        init();

        $(window).resize(function() {
                init();
        });

    });
    </script>
</body>
</html>
[2023-05-30 14:27:26]:ERROR kotlin.Unit
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 5 column 2 path $
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at me.fycz.sduseat.Main.loginAndGetSeats(Main.kt:112)
        at me.fycz.sduseat.Main.loginAndGetSeats$default(Main.kt:103)
        at me.fycz.sduseat.Main.main(Main.kt:78)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 5 column 2 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
        at com.google.gson.JsonParser.parseString(JsonParser.java:47)
        at me.fycz.sduseat.utils.GsonExtensionsKt.parseString(GsonExtensions.kt:84)
        at me.fycz.sduseat.http.OkHttpUtilsKt.json(OkHttpUtils.kt:85)
        at me.fycz.sduseat.http.OkHttpUtilsKt.json$default(OkHttpUtils.kt:84)
        at me.fycz.sduseat.api.IAuth.device(IAuth.kt:91)
        at me.fycz.sduseat.api.Auth.login(Auth.kt:51)
        at me.fycz.sduseat.Main.authRunnable$lambda-1(Main.kt:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 5 column 2 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1404)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
        ... 12 more
哥，你能帮我看看这上面是什么问题吗？前两天还正常，今天突然就这样了

**Comment by N1necats** [comment]
再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿

**Comment by fengyuecanzhu** [comment]
我晚上看看

**Comment by fengyuecanzhu** [comment]
> 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿

我号也没问题，没法复现定位错误

**Comment by N1necats** [comment]
> > 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿
> 
> 我号也没问题，没法复现定位错误

好吧，麻烦了，谢谢！

**Comment by fengyuecanzhu** [comment]
> > > 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿
> > 
> > 
> > 我号也没问题，没法复现定位错误
> 
> 好吧，麻烦了，谢谢！

你试试这个（先解压）
[sdu-seat-2.7.zip](https://github.com/fengyuecanzhu/Sdu-Seat/files/11600678/sdu-seat-2.7.zip)

**Comment by N1necats** [comment]
麻烦哥了，我试了，这次显示设备验证失败，我重新按你的方法再获取了一次设备id，但还是不行QAQ。你能给我再发一个我已经很感动了，实在不行也没关系，感觉这不是我一个文科生能用得了的哈哈哈，最近期末月约的人多了，我还是自己手动抢好一些，谢谢啦！！！
这是具体的问题反馈：
[2023-05-30 23:09:08]:ERROR             json解析错误，内容如下:



<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="renderer" content="webkit">
        <link rel="stylesheet" type="text/css" href="/cas/comm/icon/icon.css">
    <link rel="stylesheet" type="text/css" href="/cas/comm/icon/ie7/ie7.css">
    <link rel="stylesheet" type="text/css" href="/cas/comm/css/login.css">
        <script type="text/javascript" src="/cas/comm/icon/ie7/ie7.js"></script>
        <title>系统提示</title>
</head>
<body class="bind_bg" style="height: 100%;">
    <div class="bind_container">
        
        <div class="password_container_header">
                <div class="password_header_inside">
                        <p class="logo-picture">
                                <img class="password_logo_pic" src="/cas/comm/images/head_logo.png">
                        </p>
                        <p class="logo-point"></p>
                        <p class="logo-text">系统提示</p>
                        <p class="clear"></p>
                </div>
        </div>
        <div class="logo_light"></div>
        <div class="bind_main_container">
            <img class="authorise_img" src="/cas/comm/image/unauthorise.png">
            <span class="authorise_title">请求出错</span>
            <p class="unauthorise_p">抱歉！您的请求出现了异常，请稍后再试。</p>
            <input class="bind_button left bind_button_1 authorise_button" type="button" value="重新登录" id="btn_login">
            <input class="bind_button right bind_button_2 authorise_button" type="button" value="关闭页面" id="btn_close">
        </div>
    </div>

    <script type="text/javascript" src="/cas/comm/js/jquery.min.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#btn_close").click(function(){
                window.open("about:blank","_self").close();
        });

        $("#btn_login").click(function(){
                location.href="/cas/logout?service=http://service.sdu.edu.cn/tp_up/view?m=up";
        });

        var setting = {
                imageWidth : 1680,
                imageHeight : 1050
        };
        var init = function() {
                var windowHeight = $(window).height();
                var windowWidth = $(window).width();
//              $(".login_conatiner").height(windowHeight).width(windowWidth);
                $(".login_conatiner").css("height",windowHeight);
                $(".login_conatiner").css("width",windowWidth);

//              $("#container_bg").height(windowHeight).width(windowWidth);
                $("#container_bg").css("height",windowHeight);
                $("#container_bg").css("width",windowWidth);

//              $("#login_right_box").height(windowHeight);
                $("#login_right_box").css("height",windowHeight);

                var imgW = setting.imageWidth;
                var imgH = setting.imageHeight;
                var ratio = imgH / imgW; // 图片的高宽比

                imgW = windowWidth; // 图片的宽度等于窗口宽度
                imgH = Math.round(windowWidth * ratio); // 图片高度等于图片宽度 乘以 高宽比

                if (imgH < windowHeight) { // 但如果图片高度小于窗口高度的话
                        imgH = windowHeight; // 让图片高度等于窗口高度
                        imgW = Math.round(imgH / ratio); // 图片宽度等于图片高度 除以 高宽比
                }

                $(".login_img_01").width(imgW).height(imgH); // 设置图片高度和宽度
        };

        init();

        $(window).resize(function() {
                init();
        });

    });
    </script>
</body>
</html>
[2023-05-30 23:09:08]:ERROR kotlin.Unit
java.util.concurrent.ExecutionException: me.fycz.sduseat.AuthException: 设备验证失败：未知错误
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at me.fycz.sduseat.Main.loginAndGetSeats(Main.kt:112)
        at me.fycz.sduseat.Main.loginAndGetSeats$default(Main.kt:103)
        at me.fycz.sduseat.Main.main(Main.kt:78)
Caused by: me.fycz.sduseat.AuthException: 设备验证失败：未知错误

**Comment by fengyuecanzhu** [comment]
> > > 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿
> > 
> > 
> > 我号也没问题，没法复现定位错误
> 
> 好吧，麻烦了，谢谢！

如果有空再试试这个，应该没问题了（再有问题我也没办法了）
[sdu-seat-2.7.zip](https://github.com/fengyuecanzhu/Sdu-Seat/files/11607431/sdu-seat-2.7.zip)

**Comment by N1necats** [comment]
> > > > 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿
> > > 
> > > 
> > > 我号也没问题，没法复现定位错误
> > 
> > 
> > 好吧，麻烦了，谢谢！
> 
> 如果有空再试试这个，应该没问题了（再有问题我也没办法了） [sdu-seat-2.7.zip](https://github.com/fengyuecanzhu/Sdu-Seat/files/11607431/sdu-seat-2.7.zip)

谢谢哥，好像还是有点问题，麻烦啦
[2023-05-31 08:53:19]:ERROR kotlin.Unit
java.util.concurrent.ExecutionException: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at me.fycz.sduseat.Main.loginAndGetSeats(Main.kt:112)
        at me.fycz.sduseat.Main.loginAndGetSeats$default(Main.kt:103)
        at me.fycz.sduseat.Main.main(Main.kt:78)
Caused by: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证

**Comment by fengyuecanzhu** [comment]
> > > > > 再借了两个号试了试，有一个号也是上面这样的情况，还有一个正常。麻烦哥指点一二，可有偿
> > > > 
> > > > 
> > > > 我号也没问题，没法复现定位错误
> > > 
> > > 
> > > 好吧，麻烦了，谢谢！
> > 
> > 
> > 如果有空再试试这个，应该没问题了（再有问题我也没办法了） [sdu-seat-2.7.zip](https://github.com/fengyuecanzhu/Sdu-Seat/files/11607431/sdu-seat-2.7.zip)
> 
> 谢谢哥，好像还是有点问题，麻烦啦 [2023-05-31 08:53:19]:ERROR kotlin.Unit java.util.concurrent.ExecutionException: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证 at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at me.fycz.sduseat.Main.loginAndGetSeats(Main.kt:112) at me.fycz.sduseat.Main.loginAndGetSeats$default(Main.kt:103) at me.fycz.sduseat.Main.main(Main.kt:78) Caused by: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证

那就是设备ID获取的有问题了，试试下面的脚本获取的设备ID（这设备验证搞了两个ID，先试试下面的能不能过，不能过的话我再给配置加个ID）
```js
Fingerprint2.get(function(components){var details_s = "" ;for (var index in components) {var obj = components[index];if(obj.key == 'deviceMemory'||obj.key == 'screenResolution'||obj.key == 'availableScreenResolution'){continue ;};var line = obj.key + " = " + String(obj.value).substr(0, 100);details_s+= line+"\n";};console.log(Fingerprint2.x64hash128(details_s, 31));})
```

**Comment by N1necats** [comment]
我靠哥，真的可以了！太感谢了，要不哥你加个v我请你喝杯奶茶吧！

**Comment by fengyuecanzhu** [comment]
> 我靠哥，真的可以了！太感谢了，要不哥你加个v我请你喝杯奶茶吧！

这倒不用，谢谢了

**Comment by N1necats** [comment]
那再谢谢哥了，这两次麻烦你了，以后要是有什么需要的可以随时再找我，我学法的

**Comment by fengyuecanzhu** [comment]
> 那再谢谢哥了，这两次麻烦你了，以后要是有什么需要的可以随时再找我，我学法的

没事，我加下你q（v搜不到），有问题直接q上找我

**Comment by N1necats** [comment]
抱歉抱歉，之前没设置能通过手机号搜到，现在好了，麻烦再加一次吧
